# Generated by Django 6.0.1 on 2026-01-28 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='post_author',
        ),
    ]
